name: asset_catalog
description: asset documentation tools for flutter projects
version: 0.3.1
homepage: https://github.com/thought-lab
repository: https://github.com/thought-lab/asset_catalog
issue_tracker: https://github.com/thought-lab/asset_catalog/issues

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

